### ISSUE TITLE
Add source code URL override to docs system

### ISSUE THREAD

**Issue by Derpius** [thegrb93/StarfallEx#1181]
Add `-- @src` or equivalent as an optional parameter in documentation comments to override the auto generated source code URL (for custom libraries).  

To maintain standardisation with the rest of the docs it'd probably be a good idea to whitelist GitHub URLs only.

**Comment by Vurv78** [comment]
Nevermind npm is completely broken for me and there's like 200 dependencies for the docs (thanks react) that are either 1. Deprecated/Archived 2. Broken due to new npm. Downgrading doesn't work for me either. I have the code if anyone else can do it, should work.

https://github.com/Vurv78/StarfallEx/commit/0ec4537349d7d4df7acd1b0b53e83d267978ff39

Replace Modules/Links.js with this:
```js
const IS_SHORTSRC = /^libs_\w+/;

// Returns a link to the github's starfall source code so that the
// local url given can be used.
// You get 'properties' from the cards initial args/
// 'path' may be something like libs_sh/math.lua#L124 or <ghpath>/file.lua#L124
export default function getGitSourceLink(properties) {
    let path = properties.ghpath;
    if ( IS_SHORTSRC.test(path) ) {
        return "https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/" + path;
    }
    return "https://github.com/" + path;
}
```
Might come back to it later but It's already been a while and I haven't been able to make any progress. Don't want to leave a dead issue with no results.

(Also rewriting this in svelte would be nice to solve dependency hell)

**Comment by thegrb93** [comment]
npm works for me so I can probably do it

**Comment by Vurv78** [comment]
Thanks, tried to audit (even manually) but it would just lead to more errors... :/
