### ISSUE TITLE
Allow including files from HTTP

### ISSUE THREAD

**Issue by szymski** [thegrb93/StarfallEx#1185]
First step to allow GitHub repo imports and a cool feature anyways.

SF.Editor.BuildIncludesTable needs some refactoring - it's partially synchronous and callback code at the same time.
I see it that way - we can have different file "resolvers" which load file contents depending on the parameter passed to --@include directive. One type of resolver is obviously the local filesystem resolver. Another - the one this issue is about - an http file resolver. And finally, GitHub/GitLab (or git in general, dunno if that's easy to achieve) resolver.

**Comment by szymski** [comment]
I started experimenting by adding support for these custom resolvers.

**Comment by Cheatoid** [comment]
What's wrong with cloning the repo manually inside of your `data/starfall/<repo>` folder and then `--@include`-ing it??

**Comment by Vurv78** [comment]
> What's wrong with cloning the repo manually inside of your `data/starfall/<repo>` folder and then `--@include`-ing it??

You can't legitimately ask some dude to clone your repo and then manually type ``--@include``, require, etc for every small library..
That's kind of similar to why starfall/e2 exists, to make small projects without the hassle of a full addon.

Also it'd be so much nicer to be able to organize your libraries on github rather than ask someone for a file and manually copying it.

Imagine just saying, here's my library ..., add ``--@using Vurv78/Test`` to use it (Which would redir to ``Vurv78/SFLibs/Test``).. so much nicer.

> Because if you're going to do this like ``--@include <git url here>`` feature, then you're gonna get screamed at for also not adding support for BitBucket, Gogs, Gitea, SVN (Tortoise/Apache/Mercurial), etc. etc. :D

Anyone else can implement these probably, although that's pandering to a miniscule (if any) population

**Comment by Cheatoid** [comment]
> I think the goal was to link to the urls of raw text files, not repos.

Then I don't see the point, since anyone could already do this in a way I am about to show (down below)...

> Also it'd be so much nicer to be able to organize your libraries on github rather than ask someone for a file and manually copying it.
> Imagine just saying, here's my library ..., add `--@using Vurv78/Test` to use it (Which would redir to `Vurv78/SFLibs/Test`).. so much nicer. And it could be updated automatically.

I don't understand at all, how exactly you intend for `Vurv78/Test` to expand to `Vurv78/SFLibs/Test` automagically, and what file would that even pull, how do you determine the path if the file is somewhere in folder?  
Do you expect everyone to have their repos called exactly `SFLibs`?! How would that work if I have multiple repos?  
So to me, such design looks more confusing than helpful.

Moreover, how would you figure out what branch to use (without querying GH REST API), for example, everyone is moving away from `master` to `main`, and of course there's also the case that some people prefer to use `dev` as their "main" branch name.

Another concern to top it all off, how would you handle submodules in such SF library repos? Which is how I would pull 3rd party dependencies into my own "SF libraries" repo (if I had one), but if you can't pull these submodules/dependencies, then that would mean my libraries won't work. Making this even bigger mess.

And what about private repos?

-----

For **public single-file SF library without dependencies**, which appears to be what `--@using` is attempting to solve, anyways...
Here goes how I would solve this right now, quick enough and no magic, everyone can do it already and also it is *not* limited to GitHub-only:
```lua
-- busy right now, will post code later.
```

Note: The only requirement for this to work, is that you must have `http.get` permission set to at least `Owner only` (if you have it set to `Noone` this won't work, obviously).  
If the library is required on server-side, it is downloaded and streamed from owner to server and then executed once received on server-side ([`loadstring`](http://thegrb93.github.io/StarfallEx/#Libraries.builtins.loadstring)).
Very simple and straightforward...

**Comment by Cheatoid** [comment]
Let me point out yet another problem:
Let's say `--@using` is a thing, and everyone is using it, all is good in world... and you're relying on someone's SF library to work, and then one day, a developer introduces a bug or rather a breaking change in their SF library. *oh no!* :trollface:
This means you have 3 options, forcing you to either:
- "Fix" your own SF code to mitigate the breaking change.
- Rollback to prior version of *xxx* SF library when it was working fine. But here is a thing, from what you described above, `--@using` does not offer such functionality, so you'd have to go manually look at commit/history in order to download older version of *xxx* SF library and then copy it... which also means you're gonna need to stop using `--@using` at that point. how sad.
- Stop using *xxx* SF library altogether and make your own.

**Comment by Vurv78** [comment]
You're making this up to be something too powerful. ``--@using`` would just check a repo and scan for the file you are trying to use. If the library owner updates it, that's on the user. There might be a simple way to get a raw file at a commit but right now I don't really wanna think about it.

> I don't understand at all, how exactly you intend for Vurv78/Test to expand to Vurv78/SFLibs/Test automagically, and what file would that even pull, how do you determine the path if the file is somewhere in folder?
Do you expect everyone to have their repos called exactly SFLibs?! How would that work if I have multiple repos?
So to me, such design looks more confusing than helpful.

Yes, either that or we'd have to deal with long gross paths constantly for no good reason. ``--@using Vurv78/SFLibs/Test`` over ``--@using Vurv78/Test``. I like the second because it has more emphasis on the author and the library rather than github. I see no reason why anyone wouldn't/couldn't use a single repo for their starfall libraries.

> Another concern to top it all off, how would you handle submodules in such SF library repos? Which is how I would pull 3rd party dependencies into my own "SF libraries" repo (if I had one), but if you can't pull these submodules/dependencies, then that would mean my libraries won't work. Making this even bigger mess.

Don't want dependency hell, these libs shouldn't have any dependencies. Also we've already said this is just including text files. I don't think ``--@include --@using require()`` should work in these libraries.

> Moreover, how would you figure out what branch to use (without querying GH REST API), for example, everyone is moving away from master to main, and of course there's also the case that some people prefer to use dev as their "main" branch name.

This is the one thing that I wouldn't know. I guess you'd have to test master+main (thanks github..) every time..?

> Let's say ``--@using`` is a thing, and everyone is using it, all is good in world... and you're relying on someone's SF library to work, and then one day, a developer introduces a bug or rather a breaking change in their SF library. oh no! :trollface:

That's up to the library user and the library creator. If they break their code that's on them. That's just how dependencies work. This is like using the workshop.

> Rollback to prior version of xxx SF library when it was working fine. But here is a thing, from what you described above, ``--@using`` does not offer such functionality, so you'd have to go manually look at commit/history in order to download older version of xxx SF library and then copy it... which also means you're gonna need to stop using ``--@using`` at that point. how sad.

If we add support for specific commits then that'd be fine. I don't think it should be that hard to resolve to a specific commit

> And what about private repos?

Why would you try and include a private library..? At that point you're the one who created it, just save it locally.

**Comment by Cheatoid** [comment]
> If we add support for specific commits then that'd be fine. I don't think it should be that hard to resolve to a specific commit

Right, it is not hard to do, but the question is how would the syntax look like? Because I can't come up with a clean/neat syntax which would allow a user to precisely specify domain name (gitlab/github/gist/bitbucket/etc), file path and name, branch name (master/main/dev/etc) and/or particular commit hash on a single line.
For this reason, I think it is best to just use an absolute URL, because then there is nothing to do with "custom resolvers".
Because eventually, you will end up with the case where you want to use someone's SF single-file library, but it is uploaded and maintained on pastebin/gist/etc.
Using absolute URL overcomes all of this headache, including domain/host, different branches and different commit/version... all of those cases are already handled then. It is just up to user to use more specific URL, in case of breaking change.
