### ISSUE TITLE
Incompatibility with EasyChat

### ISSUE THREAD

**Issue by licen150** [thegrb93/StarfallEx#1232]
Hi, when working with EasyChat i get a small error  EasyChat github: https://github.com/Earu/EasyChat
Bug: https://www.youtube.com/watch?v=xkv7QWKhae0

**Comment by thegrb93** [comment]
Best solution is to change https://github.com/Earu/EasyChat/blob/master/lua/easychat/easychat.lua#L755 str:find to string.find(str. I don't think there's anything starfall can do to fix this

**Comment by thegrb93** [comment]
You can also wrap your erroring function with pcall to hopefully catch the error without messing up whatever function you were trying to do.

**Comment by Python1320** [comment]
Hmm, or maybe wrap the AddText into a queue so the starfall context doesn't process them at all? 
Although probably a valid fix it would likely reoccur in some other chatbox or anything else.

The question remains which side should have a queue:

On the other hand I don't see EasyChat as one that should make AddText wrapped except to prevent stupid spam mistakes. I mean if I accidentally ran AddText 10k times it would not lag if the queue was 100 messages long. In this sense it would make architecturally sense to put it to easychat side to prevent this on starfall and anything else globally.

Starfall can't mandate other addons to know about these additional restrictions and I don't see a way to switch context without super penalty in perf. This would happen with non-easychat also so starfall would be protected from any similar problems if queue was on that side.

In this light both sides could implement a queue... 
I don't even see a clear winner anymore except one has to do it at least. 
Since Starfall is the one changing the rules I would say starfall would have to add a buffer to hide any extra complexity from chatboxes and the like. 
One tick delay on chat messages should not break anything on starfall side either, famous last words.

**Comment by thegrb93** [comment]
I don't know what a queue would accomplish. The issue is the addon is triggering starfalls regex safety because its using the starfall string library via string.__index. The real solution is gmod dev to implement https://github.com/Facepunch/garrysmod-requests/issues/1878
