### ISSUE TITLE
Hook 'render' errored with: addons/scb-20/lua/scb/cl_util.lua:132: Regex is too complex! 5 ext search length too long (40 max) 

### ISSUE THREAD

**Issue by testeron211** [thegrb93/StarfallEx#1240]
`ver. = 4.5 (Release)`

Error on `printTable()` and `print()` only on 4.5
ver. 4.4 haven't that problem

```lua
[notify]: Hook 'render' errored with: addons/scb-20/lua/scb/cl_util.lua:132: Regex is too complex! 5 ext search length too long (40 max) 
stack traceback:
	addons/scb-20/lua/scb/cl_util.lua:132: in function 'find_url'
	addons/scb-20/lua/scb/vgui/scb_chat_line.lua:590: in function 'Parse'
	addons/scb-20/lua/scb/cl_overrides.lua:143: in function 'AddText'
	addons/starfall/lua/starfall/libs_sh/builtins.lua:576: in function 'print'
	addons/starfall/lua/starfall/libs_sh/builtins.lua:413: in function 'printTableX'
	addons/starfall/lua/starfall/libs_sh/builtins.lua:595: in function 'printTable'
	SF:vizual.txt:37: in function <SF:vizual.txt:32>

```

**Comment by Vurv78** [comment]
This is because ever since release 4.5 lua pattern functions have been nerfed since they can easily lag/crash your game.
Starfall has to edit the string metatable in order to keep everything sandboxed, which ends up affecting other addons if they use the ``(""):foo()`` format versus ``string.foo("")``.

Since this addon ``scb-20`` overrides chat.AddText it's not very viable to fix here (Why does this detour exist anyway..)

So either
* The original gmod issue needs to be fixed here: https://github.com/Facepunch/garrysmod-requests/issues/1878
* The addon in question needs to replace their use of (""):foo() with string.foo("")

**Comment by testeron211** [comment]
waiting Rubat...
