### ISSUE TITLE
Custom convar / concommands

### ISSUE THREAD

**Issue by Vurv78** [thegrb93/StarfallEx#1243]
Allow users to create their own concmds / convars that would be prefixed by ``sf_custom_con(cmd|var)``.
Maybe would be owner-only or restricted to being in a hud/seat or I'm not sure how to deal with several sf's trying to make the same convar/concmd name. These could autocomplete from sf_custom_... and would be cleaned on chip deletion

Concept:
```lua
concmd.add("foo", function(ply, cmd, args, argStr)
	print(argStr) -- "bar"
end)
-- concmd.remove("foo")
```
Call with
``sf_custom_concmd foo bar``

And
```lua
local CVar = convar.add("foo")
print(CVar:GetInt())
```
``sf_custom_convar foo 55``

**Comment by x4fx77x4f** [comment]
This sounds quite useful for data entry.
Would probably also want to create equivalents for `incrementvar`, `multvar`, and `toggle`.
I'd also add a hook that gets run when a non-existent command/cvar is used [(vaguely similar to Garry's Mod's `concommand.Run` callback)](https://wiki.facepunch.com/gmod/concommand.Run).

> I'm not sure how to deal with several sf's trying to make the same convar/concmd name.

Could require the first parameter to be the entindex of the chip, or maybe the Steam ID of the owner of the chip. If someone types `sf_custom_concmd foo`, autocomplete might recommend `sf_custom_concmd 619 foo` and `sf_custom_concmd 623 foo`, if 619 and 623 are the entindexes of two chips that have defined `foo`.
To allow for binds, one could have StarfallEx guess which of multiple chips to use the command from in the event of conflict, use a reserved entindex like 0 or -1, or some kind of keyword like "auto" in place of the first parameter. You'd want it to always prefer chips owned by the person running the command, and then maybe go in the order of oldest chips to newest chips.

I feel like the terminology should be changed, since they aren't *actually* commands or cvars. Maybe it should be something like `sf_message_chip <entindex> [parameters]...`, and it could be made to behave more like the existing `remote` hook.

**Comment by thegrb93** [comment]
If it's all client-side and owner only, you could just give full access to the glua functions.

**Comment by thegrb93** [comment]
Pretty niche usage, I think most players prefer chat. Feel free to PR if you want to add it
