### ISSUE TITLE
Serverside starfall code leak on runtime error

### ISSUE THREAD

**Issue by checkraisefold** [thegrb93/StarfallEx#1295]
If a chip with the server directive errors and the instance is still there, the source is replicated to every client and can be read. Tested with clientmain directive, same issue.

**Comment by thegrb93** [comment]
What do you mean replicated? You mean sent? I don't recall sending code when an error happens. If you mean the error message/stack trace, that's normal

**Comment by x4fx77x4f** [comment]
If a runtime error happens serverside as soon as the chip is placed (so not in a hook, timer, or callback), serverside code will be sent to clients when it otherwise wouldn't. This also seems to happen for compilation errors, although it's a bit harder to check since it tends to result in the clientside instance being destroyed, so I can't just check `instance.source`.

Flash this code to two chips, and reflash as needed until one is dead and the other is not.
```lua
--@server
-- FAIL
if math.random(0, 1) >= 0.5 then
    error("unlucky")
end
```
Look at each one and run this command: `lua_run_cl for k, v in pairs(LocalPlayer():GetEyeTrace().Entity.instance.source) do print(k, v:sub(1, 50):gsub('\n', ''), #v) end`
On the dead chip, it will print `main	-- Server only	14`. As to be expected, the serverside code is replaced with `-- Server only`, so the only information disclosed is the path.
On the live chip, it will print `main	--@server-- FAILif math.random(0, 1) >= 0.5 then	76`. This is bad, as it could allow for unintended disclosure of code and secrets.

**Comment by x4fx77x4f** [comment]
I was making a PR, but my god, you were fast. Well done.
This appears to resolve the issue. I tested with the command from earlier, as well as inserting the following code after line 105 of `lua/entities/starfall_processor/cl_init.lua` in 1d8fbf8:
```lua
print(sfdata)
if istable(sfdata) then
	PrintTable(sfdata)
end
```
Other scripts I used to test:
Bare:
```lua
--@server
-- FAIL
--@include ./includeme.txt
```
`includeme.txt`:
```lua
-- FAIL
-- Include me!
$$$INVALID$$$
```
Bare:
```lua
--@server
-- FAIL
$$$INVALID$$$
```
I also tested with the project I was working on when I first discovered the issue, which was 21 minutes before this issue was made.
