### ISSUE TITLE
Add permission to hide other people's chat messages

### ISSUE THREAD

**Issue by NullLikesNothing** [thegrb93/StarfallEx#1379]
It would be a really nice permission to hide other people's messages with a permission.
Examples of this would be cases where you have some private chat message that shouldn't be shown for other people.
On PlayerSay hooks if the person that sent the message has granted the permission you could `return ""` to hide it

**Comment by adamnejm** [comment]
Would be nice to have for scripts that other players can interact with via chat commands, but AFAIK at this time Starfall doesn't have a way of handling clientside permissions  on serverside *([and vice versa???](https://github.com/thegrb93/StarfallEx/issues/770#issuecomment-716206420))*, so that whole system would have to be implemented.

**Comment by thegrb93** [comment]
E2 would still be able to sniff the player messages even if you try to hide them. Such is a garrysmod limitation. I don't think will be added.
