### ISSUE TITLE
With multiple players and multiple chips, some joining players don't get starfall initialization

### ISSUE THREAD

**Issue by sr229** [thegrb93/StarfallEx#1467]
Whenever you join a server with active chips, their client scripts never initializes on new clients, which meant even if you add a hook specifically for newly joined players, it will never work.

This was tested on Meta Construct Servers and on LAN as well, and I can confirm the behavior has been reproduced extensively.

**Comment by Haniasita** [comment]
Just here to second this issue on the same server. I have a chip that, among other things, has a simple "Ping" function that checks whether the clientside of the chip is running on a player or not.

It never works on newly joined players unless I repaste the chip.

**Comment by ANormalTwig** [comment]
Doesn't meta construct have a custom sf version

**Comment by Haniasita** [comment]
> Doesn't meta construct have a custom sf version

Following some testing by one of the players, it appears that we have this version of Starfall running, not the custom version.
(The latest commit on this repo, the updated whitelist, is working on our server)

**Comment by Haniasita** [comment]
Here is a Starfall script that demonstrates the issue :

https://raw.githubusercontent.com/Haniasita/MetastructAssets/main/Scripts/starfall_playerPingFailureDemonstrator.txt

To use :
1. Paste the chip in a multiplayer game
2. Type .sf_ping to get a list of players running the clientside
3. Wait for a player to join after the chip has been pasted
4. Ping again (You should notice that newly joined players do not ping back)

**Comment by ANormalTwig** [comment]
```lua
if SERVER then
    hook.add("PlayerInitialSpawn", "", function(ply)
        print("Player", ply:entIndex(), "PlayerInitialSpawn")
    end)

    net.receive("message", function(_, ply)
        print("Player", ply:entIndex(), "Net Message")
    end)

    hook.add("ClientInitialized", "", function(ply)
        print("Player", ply:entIndex(), "ClientInitialized")
    end)

    return
end

net.start("message")
net.send()
```
![image](https://github.com/thegrb93/StarfallEx/assets/78218557/e21ffee6-a4b9-45c6-bf41-24f479d575e3)
![image](https://github.com/thegrb93/StarfallEx/assets/78218557/52dae59f-c007-417a-9e2a-170b10f94a29)
Seems to work fine, you probably have an addon or script that's messing with StarfallEx. Consider talking to an admin or developer of Meta Construct.

**Comment by Haniasita** [comment]
Thank you for the feedback @ANormalTwig, I've forwarded this to Metastruct issues. I assume that this issue can be closed if it does not affect StarfallEx as a whole.

**Comment by Python1320** [comment]
Meta has no custom starfall. I could reproduce the problem intermittently (see below) but I have no idea what is going wrong yet. 
Could you reproduce the problem in LAN for real?

It seems that the problem can be reproduced if:
 1. There are multiple starfalls and multiple players
 2. You spawn your otherwise working starfall (clinit works from everyone just fine)
 3. A player joins (this player has broken clinit initializations)

I made a logger for initialization and got some strange results:
```lua
-- serverside

net.Receive("starfall_processor_clinit", function(len, ply)
	local proc = net.ReadEntity()

	if not ply:IsValid() or not proc:IsValid() then
		print("clinit FAIL", ply, proc)

		return
	end

	local instance = proc.instance

	if not instance then
		print("clinit FAIL2", ply, proc)

		return
	end

	print("clientinitialized", ply, proc)
	instance:runScriptHook("clientinitialized", instance.Types.Player.Wrap(ply))
end)
```
I made an AFK player rejoin and got this
```lua
clientinitialized Player [2][Juha] Entity [3613][starfall_processor]
clientinitialized Player [2][Juha] Entity [3612][starfall_processor]
clientinitialized Player [2][Juha] Entity [3899][starfall_processor]
clientinitialized Player [2][Juha] Entity [3787][starfall_processor] <- mine
clinit FAIL2 Player [2][Juha] Entity [1971][mining_ore]
```
This time it worked: ![image](https://github.com/thegrb93/StarfallEx/assets/207340/f49b28fc-e21c-469b-a5b4-90ff4c6d19f7)

... but somehow one of the initializations was for a completely invalid entity altogether. 

Not sure how any code on meta can break things this bad, will keep you updated, but I wouldn't rule out it being a game or starfall bug yet. Just a more complex one (?)

On another rejoin attempt my starfall for the player contained a `mainfile` that did not exist related to the `sfdata`  (`self.sfdata.files[self.sfdata.mainfile]` was `nil` although both existed) and the contents were for a different player's starfall altogether.

**Comment by Haniasita** [comment]
I have successfully reproduced this bug in a LAN server completely unrelated to Metastruct, running release tag 2.8 :

- 3 players online
- Several Starfall chips with client code, pasted around by different players
- Player 2 rejoins, "PlayerInitialSpawn" gets run, clientside is never initialized for them, they see all Starfall screens black
- Player 3 rejoins, the Starfall clientside gets properly initialized, they see Starfall screens fine
- Player 2 rejoins again, "PlayerInitialSpawn" gets run, clientside is never initialized for them, they see all Starfall screens black

**Comment by thegrb93** [comment]
> Still don't know why this would happen, but apparently it does. So we can't assume ordering like this even if code was perfect and never errored.

I believe we removed all assumptions of order a long time ago. It might be possible an old version of advdupe2 or pac3 could be overriding that update.

**Comment by Python1320** [comment]
Sorry, I did not see this part https://github.com/thegrb93/StarfallEx/blob/a64078e0930a9e4b53974ff30213d88138d63fe0/lua/autorun/netstream.lua#L216 so it can't be the stream order after all... this will require further investigation.

**Comment by thegrb93** [comment]
Maybe a test with sending multiple writeStreams would help narrow down the issue.

SV
```lua
for i=1, 10 do
net.Start("testWrite")
net.WriteUInt(i, 8)
net.WriteStream(string.rep(i,1024*8))
net.Send(ply)
end
```

CL
```
net.Receive("testWrite",function()
local i = net.ReadUInt(8)
net.ReadStream(function(data)
    if string.find(data,"[^"..i.."]") then print("Data mismatch with "..i) else print("Data matches "..i) end
end)
end)
```

**Comment by thegrb93** [comment]
Could this be failing? Or are you certain it's a networking bug?

https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/sflib.lua#L1069-L1081

**Comment by Python1320** [comment]
I tested `SF.WaitForPlayerInit` and it is being called. 
I made two players rejoin and they get starfall data from a wrong chip. 
![image](https://github.com/thegrb93/StarfallEx/assets/207340/221bb870-3c2a-4e92-b39d-4ff448dd39f6)

On a positive note right after the chip spawn everyone (20 players) get the right data from the right chip, at least. Something special to do with spawning.

Still need to establish that this is also a problem on other servers, might be somewhat hidden due to the very specific conditions required.

**Comment by Python1320** [comment]
Still haven't had time, but if I run all `SF.WaitForPlayerInit` hooks on everyone manually I can see that every player currently ingame gets the files corrected again for each entity. 
Still haven't ever observed `ent.sfdata.mainfile` being wrong, just the `ent.sfdata.files` table.

**Comment by Denneisk** [comment]
I experience this on NPCZ :P
