### ISSUE TITLE
Avoid netstream overwriting

### ISSUE THREAD

**Issue by Denneisk** [thegrb93/StarfallEx#1573]
As far as I know, netstream doesn't get updated much, but if someone wanted to modify it, that could cause quite a bit of problems as the library isn't built with forward-compatibility/mixed versions in mind. Having netstream named the same in `autorun/` will cause collisions. I would recommend a new format that avoids this. The old style of having it defined in the addon's lua folder was good for this.

I would also suggest moving netstream to its own repo just to make contributing to it more explicit.

**Comment by Vurv78** [comment]
You shouldn't have to change the netstream code. It's meant to override since it's just stable utility that shouldn't need any updates. It was meant for garrysmod to merge originally.

And if you do make any breaking changes you'd have to get it through all the major addons that use it (so you should have a really good reason why you're changing it)

(advdupe, starfall, pac, prob others)

**Comment by thegrb93** [comment]
Yeah, gmod has always a lack of good dependency resolution. You used to see addons including their own copies of 'von' and such.

**Comment by thegrb93** [comment]
The main reason netstream can only have one instance is so multiple netstreams packaged with other addons don't do work at the same time and then cause network overflows. All addons should be using the same lib.

**Comment by thegrb93** [comment]
Also one last tidbit of info is, if a server wants to tweak the variables of netstream, they should do it by using an initialize hook and editing the variables, rather than editing netstream itself. Maybe I should've made those convars.
