### ISSUE TITLE
Wirelinks Return Empty Table and Cannot Be Written To or Read From

### ISSUE THREAD

**Issue by LengthenedGradient** [thegrb93/StarfallEx#1577]
Wirelinks in Starfall seem broken. I tried using wiring a cam controller to the chip and refreshing. The result is always an empty table. When printing a specific wirelink output, the result is always nil.

```lua
--@name
--@author
--@server

wire.adjustPorts({Ent="entity"})
local ent = wire.ports.Ent
printTable(ent:getWirelink())
```

I am up to date with starfall EX's main branch (tested in SP). I'm not sure the version but I also tested on MP with the same result.

I am not sure but I am guessing it might be related to:
https://github.com/wiremod/wire/pull/2891
https://github.com/wiremod/wire/pull/2942

**Comment by adamnejm** [comment]
> The result is always an empty table

This is simply because a proper `__tostring` metamethod is not implemented for the Wirelink type *(and many other types)*. It's an issue and needs to be taken care of, but doesn't really affect the functionality, if implemented it would probably just say something like `Wirelink [203][starfall_processor]` or whatever.  
  
___

This code works fine:
```lua
--@server
wire.adjustPorts({Ent="entity"})
print(wire.ports.Ent)
```
It first prints `[NULL Entity]`, then after I wire up the entity to the chip and refresh it, then it prints the entity as usual, eg. `Entity [202][prop_physics]`.

**Comment by LengthenedGradient** [comment]
Never mind, my wire was out of date. Apologies for the inconvenience.

**Comment by adamnejm** [comment]
> The result is always an empty table

Wirelink doesn't have custom `__printtable` implemented, [see here](https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/libs_sh/builtins.lua#L447-L450).  
  
However everything seems to be working:
```lua
--@name Generic
--@author Name
--@server

local owner, client, chip, world = owner(), player(), chip(), entity(0)

-------------------------------------------

local indicator_sent = prop.createSent(chip:getPos() + chip:getUp() * 20, chip:getAngles(), "gmod_wire_indicator")

wire.adjustPorts({ Indicator = "entity" })
wire.create(chip, indicator_sent, "Indicator", "entity", 1)

local indicator_wl = wire.ports.Indicator:getWirelink()
timer.create("Blink", 0.5, 0, function()
    local current = indicator_wl:inputValue("A")
    indicator_wl.A = current == 1 and 0 or 1
end)
```
