### ISSUE TITLE
CL Error instance.lua:763

### ISSUE THREAD

**Issue by wrefgtzweve** [thegrb93/StarfallEx#1895]
I've seen this error happen daily now, im not sure what causes it or how to reproduce it as i just see it often appear in logs.
```
[starfallex] addons/starfallex/lua/starfall/instance.lua:763: attempt to compare nil with number
  1. func - addons/starfallex/lua/starfall/instance.lua:763
   2. unknown - addons/ulib/lua/includes/modules/hook.lua:260
```

**Comment by thegrb93** [comment]
The SF.playerInstances contains an empty table when it shouldn't. Gotta look into that.

**Comment by yingKatsu** [comment]
https://cdn.discordapp.com/attachments/921945120167833613/1304905421676478524/2024-11-09_14-24-29.mp4?ex=67311760&is=672fc5e0&hm=56a59544d94a55f28a1e14dd850018c855c8bac7c13fda521ebeebdba63af4ac&
latest version of gmod with only latest ver of starfall and dev library for sf

playerInstances table emptying itself for some reason.

my chips have been nonsensically "CPU Quota Reached!" erroring for a while now
noticed that their quota tooltips were freezing and not updating.
the reason why is because the quota is literally not being calculated bc the for loop that loops all instances is looping an empty table
the instances still run and delete as normal

code used:
`
local print = print
local printTable = printTable
dev.setGlobal()

print(SysTime())
for pl, insts in pairs(SF.playerInstances) do
    for instance in pairs(insts) do
        print(pl, instance.entity)
    end
end`
