### ISSUE TITLE
Add Tick hook

### ISSUE THREAD

**Issue by edgarasf123** [thegrb93/StarfallEx#38]
Tick is called every FPS instead of each game frame as Think hook does.

**Comment by ThatOneCheetah** [comment]
If I'm not mistaken the `render` hook does the exact same.

**Comment by edgarasf123** [comment]
Yes, but `tick` supposed to be used to process stuff instead of rendering stuff. Also `render` doesn't work without screen.

**Comment by ThatOneCheetah** [comment]
It seems from this code:

```
`if SERVER then return end

local curtime   = timer.curtime

local last_tick = curtime()
hook.add( "think", "test", function()
    print( 1/(curtime()-last_tick) .. "tps" )
    last_tick = curtime()
end )
```
That the `think` hook is actually called every FPS instead of every game-tick, as described [here](http://wiki.garrysmod.com/page/GM/Think); Which means the Starfall documentation is slightly off.

I've added a `tick` hook which is *actually* called every game tick [here](https://github.com/ThatOneCheetah/StarfallEx/commit/e2a7dff17099adb64a5f7843857492acc96006b9).
I'll make a pull request as soon as the net bursting fix has been merged.
