### ISSUE TITLE
Add safety to catches so they can't catch userdata from external code

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#542]

**Comment by mitterdoo** [comment]
I'm assuming this is so SF can't change anything outside of the sandboxed environment. This safety should extend to any mutable datatype, such as tables, Vectors, Angles, etc. Instead of blacklisting these types, there should be a whitelist instead, only allowing the simple Lua types: string, bool, number, and nil.

This does raise another problem, though. In the GLua environment, debug.setmetatable allows programmers to set the underlying metatable of these primitive types. Example:
```lua
content = {foo = 2}
meta = {__index = content}
debug.setmetatable(true, meta)
print( (true).foo )
print( (false).foo )```
prints `2` twice. That's fine, but there's now a new problem:
```lua
print(getmetatable(true) == meta)
```
prints `true`. This is just using the standard global `getmetatable` that Starfall uses; and just like that, the outside environment is leaking into the sandbox.
Should this be a concern in the end? This might also apply to other functions that take in primitive types. Keep in mind, this is something only people outside the SF environment can do.

**Comment by thegrb93** [comment]
SF has its ways of sanitizing things. Only if an addon sets metatable of type in the starfall execution frame will that be an issue.

**Comment by thegrb93** [comment]
I know Metastruct likes its custom metatables which is why I added that safety

**Comment by mitterdoo** [comment]
Would simply using `tostring` before calling the user callback function work then?

**Comment by thegrb93** [comment]
I think we don't want to restrict users to just strings. I'll add sensitization to the errors.
