### ISSUE TITLE
Remove joystick lib. xinput replaces it.

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#592]

**Comment by mitterdoo** [comment]
Some controllers use DirectInput, but don't use XInput. XInput is a way of standardizing controller inputs to have a directional pad, 4 buttons on the right, a start and select button, two triggers, two bumpers, two stick buttons, and two stick 2D axes. For example, I own a Wii Guitar Hero controller, and with the Raphnet adapter I own, the controller is *not* detected in XInput. This makes sense, because the controller isn't a common gamepad controller that you'd use in a FPS or something. It *is* detected by DirectInput, however.

Maybe there should be a rewrite for DInput, that uses the same hook-based, threaded polling that my XInput module uses
