### ISSUE TITLE
New doc helper HTML

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#789]
We have the Docs table generating now. Now we need the doc web app that can take the json data.

**Comment by Damianu** [comment]
Gonna try to look into it. Thought about doing simple react app and adding souce on gh as separate branch.

**Comment by thegrb93** [comment]
Comon D, new functions are missing from the helper

**Comment by thegrb93** [comment]
@Damianu if you want to start a branch and get it started, I can take a look at the javascript and such and at least start getting it integrated.

**Comment by adamnejm** [comment]
Would be nice if docs could link to file and line where the function is defined

**Comment by thegrb93** [comment]
Unnecessary. Just find-in-files/grep to locate them.

**Comment by Damianu** [comment]
newdoc_test < Addon branch
doc2 < React branch (npm run build to compile, then copy html file from build folder)

Core functionality is implemented, so hardest part is done. 
We need to get pages for specific types implemented tho, there are example ones in there already. But I'd appretiate any help I can get with that due to my limited time for gmod.

**Comment by thegrb93** [comment]
I'll start working again sometime soon. Been having too much fun with my new switch
