### ISSUE TITLE
Angle():getNormalized() fails

### ISSUE THREAD

**Issue by adamnejm** [thegrb93/StarfallEx#813]
No wonder really, trying to access tbl variable that doesn't exist
https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/libs_sh/angles.lua#L156

**Comment by thegrb93** [comment]
was removed, it's bad mathematics to rely on it anyway.

**Comment by thegrb93** [comment]
use math.angNorm

**Comment by adamnejm** [comment]
1. Backwards comatibility
2. math.normalizeAngle takes number input only
3. People start complaining about SF being broken all the time and are switching to E2
4. Does it really hurt that much?

**Comment by thegrb93** [comment]
pitch is supposed to be -90 to 90 so the implementation already made no sense; you're just going to see rotational artifacts except for special cases. You shouldn't even be doing arithmetic on Euler angles to begin with because that leads to rotational artifacts except in special cases anyway. If that's the breaking point to switch back e2 then they weren't utilizing starfall's potential anyway.

**Comment by thegrb93** [comment]
If you really need it, you can add it back by `function getMethods("Angle"):angNorm() ... end`

**Comment by thegrb93** [comment]
`Does it really hurt that much?` It's incorrect math and it encourages further incorrect math; just look at the widespread janky rotation control in chips.
