### ISSUE TITLE
Lua error after rendering for ~3 seconds

### ISSUE THREAD

**Issue by suunrider** [thegrb93/StarfallEx#9]
The code
```
if CLIENT then
    local id = render.getTextureID("icon16/arrow_refresh.png")
    hook.add( "render", "draw", function()
        render.clear( Color( 0, 0, 0 ) )
        render.setTexture( id )
        render.drawTexturedRect( 0, 0, 512, 512 )
    end )
end
```
gives after ~3 seconds the error:
```
addons/starfallex-master/lua/starfall/libs_cl/render.lua:172: attempt to index local 'mat' (a number value)
```

**Comment by thegrb93** [comment]
Yeah I made the table weak a long ago in order to deallocate unused textures, but it doesn't seem work well with numeric indexed textures. They really should have just made a wrapper instead of using integers.

If you delete ```__mode = "v",``` in render.lua then the table will no longer be weak and it will work, but there won't be anything to clean up the cached textures. I'll make a wrapper with texture limiter tomorrow.

**Comment by thegrb93** [comment]
Another solution is to switch it to use surface.SetTexture rather than using materials. No idea why they are using materials instead of textures.

**Comment by thegrb93** [comment]
Should be fixed now. Note that the texture id is no longer a number, but rather a table.
