### ISSUE TITLE
Find something that can cure the whitespace plague.

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#99]

**Comment by its-suun** [comment]
Tested `beautify` package out, and it only fixed indentation.
The code for the lua beautifier can be found [here](https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/lua-beautifier/beautifier.pl). Looks like its only about indentation

**Comment by thegrb93** [comment]
Thanks for the info. Have to find something else, or make an uncrustify plugin.

**Comment by thegrb93** [comment]
This might work https://github.com/CapsAdmin/goluwa/blob/86b7bfd6b728055725065c1e65904390608440cc/src/lua/libraries/gmod/cli.lua#L85

**Comment by Benjiko99** [comment]
IntelliJ Idea can format Lua code when you install a language plugin.
Since it's an IDE and not just a text editor, it has a pretty good understanding of the code and can do much more advanced refactorings than things like Sublime Text.
In fact, you should all give it a try as your main editor for Lua.

**Comment by its-suun** [comment]
If IntelliJ can format the code then could you try that? My formatter just lexes the code with lpeg and is really awful and takes up pretty much time.
